# Use this when you don't have storageclass

apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: s3.csi.aws.com
    volumeHandle: data-infra-s3-dev-handle
    volumeAttributes:
      region: us-west-2
      bucketName: data-infra-s3-dev
      mounter: rclone