# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-portforward-rolebinding
  namespace: airflow  # The namespace where the Role is applied
subjects:
  - kind: ServiceAccount
    name: xuguang.zhao          # The ServiceAccount name
    namespace: user             # The namespace of the ServiceAccount
roleRef:
  kind: Role
  name: service-portforward-role # Must match the Role name created above
  apiGroup: rbac.authorization.k8s.io
