# Adding a service for the R1 job: job-uci6pzxk99
apiVersion: v1
kind: Service
metadata:
  name: job-uci6pzxk99-master-0-lb
  namespace: project-llm
spec:
  selector:
    training.kubeflow.org/job-name: job-uci6pzxk99
    training.kubeflow.org/operator-name: pytorchjob-controller
    training.kubeflow.org/replica-index: '0'
    training.kubeflow.org/replica-type: master
  type: LoadBalancer
  ports:
    - name: pytorchjob-port
      protocol: TCP
      port: 30000       # external port
      targetPort: 30000 # container port matches the pod's containerPort