apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  mountOptions:
    - allow-delete
    - region=us-west-2
  csi:
    driver: s3.csi.aws.com
    volumeHandle: "pv-postgres-handle"
    volumeAttributes:
      bucket: data-infra-s3-dev
      prefix: airflow-postgres/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-airflow-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  volumeName: pv-postgres