apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-airflow-logs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: "" # Specify your storage class if needed 