apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/share/ckpt/DeepSeek-R1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deepseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-deepseek
  template:
    metadata:
      labels:
        app: ollama-deepseek
    spec:
      containers:
      - name: ollama
        image: ollama-deepseek:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: model-volume
          mountPath: /mnt/share/ckpt/DeepSeek-R1
          readOnly: true
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama-deepseek
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: LoadBalancer 