apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-shared
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ddnfs01
  resources:
    requests:
      storage: 100Ti