mappings:
  - name: Tifa-1
    src: "10.21.100.70:11434"
    dst: "ec2-13-57-59-255.us-west-1.compute.amazonaws.com:30001"
  - name: DeepSeek-1
    src: "10.27.100.157:30000"
    dst: "ec2-13-57-59-255.us-west-1.compute.amazonaws.com:30000"
  - name: R1-1776
    src: "10.21.100.78:11434"
    dst: "ec2-13-57-59-255.us-west-1.compute.amazonaws.com:30003"
  - name: Sonnet-3.7
    src: "https://llm-proxy.dev.anuttacon.com:9090"
    dst: "ec2-13-57-59-255.us-west-1.compute.amazonaws.com:30004"